version: '3.9'

services:
  linkifypostgres:
    image: postgres:15-alpine
    container_name: linkifyservice_postgres
    environment:
      POSTGRES_DB: linkifyservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  linkifyredis:
    image: redis:7-alpine
    container_name: linkify_redis
    ports:
      - "6399:6399"

  app:
    image: linkifyservice:latest
    container_name: linkifyservice_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - linkifypostgres
      - linkifyredis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/linkifyservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

volumes:
  postgres_data:
