spring:
  application:
    name: linkify-service

  datasource:
    url: jdbc:postgresql://localhost:5432/linkifyservice
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  cache:
    type: redis

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    metrics:
      access: read_only
  metrics:
    enable:
      cache: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /docs/
  swagger-ui:
    path: /api-doc/swagger-ui.html