spring:
  application:
    name: linkify-service

  datasource:
    url: jdbc:postgresql://localhost:5432/linkifyservice
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # TODO: remove later.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
